# Generated by Django 2.0 on 2018-08-09 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('balance', models.PositiveIntegerField(default=1)),
                ('mifare', models.CharField(blank=True, max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('EAN', models.IntegerField(blank=True, null=True)),
                ('active_item', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('FO', 'Food'), ('DR', 'Drink')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('paid', models.BooleanField(verbose_name=models.BooleanField(default=False))),
                ('customerForOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
                ('items', models.ManyToManyField(to='store.Item')),
            ],
        ),
    ]
