# Generated by Django 2.0 on 2018-02-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180201_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mifare',
            field=models.UUIDField(blank=True),
        ),
    ]
