# Generated by Django 2.0 on 2018-02-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20180201_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='EAN',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
