# Generated by Django 2.0 on 2018-02-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20180201_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='EAN',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
