# Generated by Django 2.0 on 2018-04-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0009_auto_20180418_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('balance', models.PositiveIntegerField(default=1)),
                ('mifare', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('EAN', models.IntegerField(blank=True, null=True)),
                ('active_item', models.BooleanField(default=True)),
                ('milliliters', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('EAN', models.IntegerField(blank=True, null=True)),
                ('active_item', models.BooleanField(default=True)),
                ('grams', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('checked_out', models.BooleanField(verbose_name=models.BooleanField(default=False))),
                ('customerForOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Drink')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Order'),
        ),
    ]
