# Generated by Django 2.0 on 2018-08-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20180418_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='orders',
        ),
        migrations.AlterField(
            model_name='customer',
            name='mifare',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
