# Generated by Django 2.0 on 2018-08-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20180806_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customerForOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Drink'),
        ),
    ]
